[colors.primary]
background = '#03303a'
foreground = '#f2f3f3'

[colors.cursor]
text = '#03303a'
cursor = '#f2f3f3'

[colors.vi_mode_cursor]
text = '#03303a'
cursor = '#4ef9fd'

[colors.search.matches]
foreground = '#083d49'
background = '#3a35fd'

[colors.search.focused_match]
foreground = '#083d49'
background = '#4ef9fd'

[colors.footer_bar]
foreground = '#083d49'
background = '#e3e7e8'

[colors.hints.start]
foreground = '#083d49'
background = '#3593fd'

[colors.hints.end]
foreground = '#083d49'
background = '#3593fd'

[colors.selection]
text = '#afb6b6'
background = '#083d49'


[colors.normal]
black   = '#083d49'
red     = '#ff536a'
green   = '#4ef9fd'
yellow  = '#3593fd'
blue    = '#6f89ff'
magenta = '#81fbfe'
cyan    = '#81bbfe'
white   = '#f2f3f3'


[colors.bright]
black   = '#677776'
red     = '#ff536a'
green   = '#4ef9fd'
yellow  = '#3593fd'
blue    = '#6f89ff'
magenta = '#81fbfe'
cyan    = '#81bbfe'
white   = '#f2f3f3'


[colors.dim]
black   = '#083d49'
red     = '#ff536a'
green   = '#4ef9fd'
yellow  = '#3593fd'
blue    = '#6f89ff'
magenta = '#81fbfe'
cyan    = '#81bbfe'
white   = '#f2f3f3'
